name: Deploy to Development

on: 
  push:
    branches:
      - devel

jobs:
  deploy:
    name: Deploy to Devel Environment
    runs-on: ubuntu-latest
    environment: devel

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '15'
          cache: 'npm'

      - name: Install Dependencies
        run: npm install

      - name: Build Application
        run: npm run build
        env:
          REACT_APP_ENV: devel

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Terraform Init
        working-directory: terraform/environments/devel
        run: terraform init

      - name: Terraform Apply
        working-directory: terraform/environments/devel
        run: terraform apply -auto-approve

      - name: Get S3 Bucket Name
        id: bucket
        working-directory: terraform/environments/devel
        shell: bash
        run: |
          set -euo pipefail
          RAW=$(terraform output -raw website_bucket_name 2>&1) || {
            echo "ERROR: terraform output failed while getting website_bucket_n
